// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import '../../../../feature/data/local/models/downloaded_model_object.dart';
import '../../../../feature/data/local/models/folder_object.dart';
import '../../../../feature/data/local/models/note_audio_object.dart';
import '../../../../feature/data/local/models/note_object.dart';
import '../../../../feature/data/local/models/note_transcription_segment_object.dart';
import '../../../../feature/data/local/models/tag_object.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1171942994289981831),
    name: 'FolderObject',
    lastPropertyId: const obx_int.IdUid(8, 1241535187019241855),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5996228167384367111),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6017727694423622233),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 8175989882408393560),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3762191945938572987),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 3651260808731296066),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2633326688251260282),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8197980829730682204),
        name: 'colorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5664310957065948106),
        name: 'iconRef',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6767305263769799139),
        name: 'updatedAt',
        type: 12,
        flags: 8,
        indexId: const obx_int.IdUid(3, 8143449237568979811),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1241535187019241855),
        name: 'createdAt',
        type: 12,
        flags: 8,
        indexId: const obx_int.IdUid(4, 8946259315907205441),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'notes',
        srcEntity: 'NoteObject',
        srcField: 'folder',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 423521120091770121),
    name: 'NoteObject',
    lastPropertyId: const obx_int.IdUid(28, 642465397112949216),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7268491314870542401),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7707547818599484435),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(5, 1085377632699562751),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2750759382940298830),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5449926154368804738),
        name: 'createdAt',
        type: 12,
        flags: 8,
        indexId: const obx_int.IdUid(6, 1240888524294916309),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7831270212002452282),
        name: 'updatedAt',
        type: 12,
        flags: 8,
        indexId: const obx_int.IdUid(7, 1927893382180319695),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8617244475630794606),
        name: 'folderId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(8, 4174505568149422228),
        relationField: 'folder',
        relationTarget: 'FolderObject',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7493323197278838229),
        name: 'audioId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(14, 1755020142853247948),
        relationField: 'audio',
        relationTarget: 'NoteAudioObject',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4576765689992024680),
        name: 'statusValue',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(15, 2964124524824995311),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4750715028724720631),
        name: 'failureReasonValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 1559236132534132468),
        name: 'originTypeValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 7026183155187473187),
        name: 'sourceDurationMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 6366208855006510413),
        name: 'transcriptionModelId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 6154735563904061009),
        name: 'transcriptionLanguageCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 7819507367509518418),
        name: 'transcribedAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 76915171422424149),
        name: 'transcriptionTaskTypeValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 4124616427789830101),
        name: 'transcriptionProcessingTimeMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 1027387402882356877),
        name: 'transcriptionStrategyValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 2451472483528487281),
        name: 'transcriptionUsedVad',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 1086817230722776559),
        name: 'transcriptionFellBackFromVad',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 5338608176825088121),
        name: 'transcriptionEmotionLabel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 3033018246150733674),
        name: 'transcriptionEventLabel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 5837524586411868322),
        name: 'transcriptionUsedItn',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 642465397112949216),
        name: 'transcriptionUsedPunctuation',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 3237763071504065953),
        name: 'tags',
        targetId: const obx_int.IdUid(3, 1306401873006046840),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'transcriptionSegments',
        srcEntity: 'NoteTranscriptionSegmentObject',
        srcField: 'note',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1306401873006046840),
    name: 'TagObject',
    lastPropertyId: const obx_int.IdUid(4, 8074129200153976669),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5266910180643961826),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3763433001657395740),
        name: 'name',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(9, 1044633193345419085),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4148179852444673318),
        name: 'colorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8074129200153976669),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'notes',
        srcEntity: 'NoteObject',
        srcField: 'tags',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 2457836903512102065),
    name: 'DownloadedModelObject',
    lastPropertyId: const obx_int.IdUid(7, 7912907317269248697),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5391374542772357954),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8834632932664524478),
        name: 'modelId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(10, 2031545194667875832),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1587299991296660354),
        name: 'modelDirName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3174670406642316400),
        name: 'localPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3388978975090142582),
        name: 'isSelected',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9082213950108349762),
        name: 'downloadedAt',
        type: 12,
        flags: 8,
        indexId: const obx_int.IdUid(11, 682868758395135203),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7912907317269248697),
        name: 'fileSizeBytes',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 8204965707487121265),
    name: 'NoteAudioObject',
    lastPropertyId: const obx_int.IdUid(6, 4790113320871467614),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6951209888339069593),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4343876194035748219),
        name: 'folderUid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(12, 5787657023071891329),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 401171000199255096),
        name: 'relativePath',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(13, 4332006373692970603),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8027888780589470466),
        name: 'sizeBytes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 489062744405119048),
        name: 'sampleRate',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4790113320871467614),
        name: 'durationMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 4797964184263632059),
    name: 'NoteTranscriptionSegmentObject',
    lastPropertyId: const obx_int.IdUid(9, 3456150181757594633),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8082808459479839842),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8650442772235002008),
        name: 'index',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(16, 4309950717671666257),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4512367934171585028),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5346844403882458932),
        name: 'startMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6828669090412699648),
        name: 'endMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2760292357492183325),
        name: 'languageCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1616652506504147375),
        name: 'tokensJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7601196147729718633),
        name: 'tokenTimestampsMsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3456150181757594633),
        name: 'noteId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(17, 2758786152635896661),
        relationField: 'note',
        relationTarget: 'NoteObject',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 4797964184263632059),
    lastIndexId: const obx_int.IdUid(17, 2758786152635896661),
    lastRelationId: const obx_int.IdUid(1, 3237763071504065953),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      1654996073209143918,
      4422751289875884364,
      8859042518604950286,
      5185384857547220289,
      2435926658032764297,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FolderObject: obx_int.EntityDefinition<FolderObject>(
      model: _entities[0],
      toOneRelations: (FolderObject object) => [],
      toManyRelations: (FolderObject object) => {
        obx_int.RelInfo<NoteObject>.toOneBacklink(
          11,
          object.id,
          (NoteObject srcObject) => srcObject.folder,
        ): object.notes,
      },
      getId: (FolderObject object) => object.id,
      setId: (FolderObject object, int id) {
        object.id = id;
      },
      objectToFB: (FolderObject object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final iconRefOffset = fbb.writeString(object.iconRef);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addInt64(4, object.colorValue);
        fbb.addOffset(5, iconRefOffset);
        fbb.addInt64(6, object.updatedAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(7, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final colorValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final iconRefParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final updatedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0) / 1000)
              .round(),
          isUtc: true,
        );
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0) / 1000)
              .round(),
          isUtc: true,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object = FolderObject(
          uid: uidParam,
          name: nameParam,
          colorValue: colorValueParam,
          iconRef: iconRefParam,
          updatedAt: updatedAtParam,
          createdAt: createdAtParam,
          id: idParam,
          description: descriptionParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<FolderObject>(
          object.notes,
          store,
          obx_int.RelInfo<NoteObject>.toOneBacklink(
            11,
            object.id,
            (NoteObject srcObject) => srcObject.folder,
          ),
        );
        return object;
      },
    ),
    NoteObject: obx_int.EntityDefinition<NoteObject>(
      model: _entities[1],
      toOneRelations: (NoteObject object) => [object.folder, object.audio],
      toManyRelations: (NoteObject object) => {
        obx_int.RelInfo<NoteObject>.toMany(1, object.id): object.tags,
        obx_int.RelInfo<NoteTranscriptionSegmentObject>.toOneBacklink(
          9,
          object.id,
          (NoteTranscriptionSegmentObject srcObject) => srcObject.note,
        ): object.transcriptionSegments,
      },
      getId: (NoteObject object) => object.id,
      setId: (NoteObject object, int id) {
        object.id = id;
      },
      objectToFB: (NoteObject object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final textOffset = fbb.writeString(object.text);
        final transcriptionModelIdOffset = object.transcriptionModelId == null
            ? null
            : fbb.writeString(object.transcriptionModelId!);
        final transcriptionLanguageCodeOffset =
            object.transcriptionLanguageCode == null
            ? null
            : fbb.writeString(object.transcriptionLanguageCode!);
        final transcriptionEmotionLabelOffset =
            object.transcriptionEmotionLabel == null
            ? null
            : fbb.writeString(object.transcriptionEmotionLabel!);
        final transcriptionEventLabelOffset =
            object.transcriptionEventLabel == null
            ? null
            : fbb.writeString(object.transcriptionEventLabel!);
        fbb.startTable(29);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, textOffset);
        fbb.addInt64(3, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(4, object.updatedAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(10, object.folder.targetId);
        fbb.addInt64(11, object.audio.targetId);
        fbb.addInt64(12, object.statusValue);
        fbb.addInt64(13, object.failureReasonValue);
        fbb.addInt64(14, object.originTypeValue);
        fbb.addInt64(15, object.sourceDurationMs);
        fbb.addOffset(16, transcriptionModelIdOffset);
        fbb.addOffset(17, transcriptionLanguageCodeOffset);
        fbb.addInt64(
          18,
          object.transcribedAt == null
              ? null
              : object.transcribedAt!.microsecondsSinceEpoch * 1000,
        );
        fbb.addInt64(19, object.transcriptionTaskTypeValue);
        fbb.addInt64(20, object.transcriptionProcessingTimeMs);
        fbb.addInt64(21, object.transcriptionStrategyValue);
        fbb.addBool(22, object.transcriptionUsedVad);
        fbb.addBool(23, object.transcriptionFellBackFromVad);
        fbb.addOffset(24, transcriptionEmotionLabelOffset);
        fbb.addOffset(25, transcriptionEventLabelOffset);
        fbb.addBool(26, object.transcriptionUsedItn);
        fbb.addBool(27, object.transcriptionUsedPunctuation);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final transcribedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          40,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0) / 1000)
              .round(),
          isUtc: true,
        );
        final updatedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0) / 1000)
              .round(),
          isUtc: true,
        );
        final originTypeValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        final statusValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final sourceDurationMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          34,
        );
        final transcriptionModelIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final transcriptionLanguageCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final transcriptionTaskTypeValueParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 42);
        final transcribedAtParam = transcribedAtValue == null
            ? null
            : DateTime.fromMicrosecondsSinceEpoch(
                (transcribedAtValue / 1000).round(),
                isUtc: true,
              );
        final transcriptionProcessingTimeMsParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 44);
        final transcriptionStrategyValueParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 46);
        final transcriptionUsedVadParam = const fb.BoolReader()
            .vTableGetNullable(buffer, rootOffset, 48);
        final transcriptionFellBackFromVadParam = const fb.BoolReader()
            .vTableGetNullable(buffer, rootOffset, 50);
        final transcriptionEmotionLabelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 52);
        final transcriptionEventLabelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 54);
        final transcriptionUsedItnParam = const fb.BoolReader()
            .vTableGetNullable(buffer, rootOffset, 56);
        final transcriptionUsedPunctuationParam = const fb.BoolReader()
            .vTableGetNullable(buffer, rootOffset, 58);
        final failureReasonValueParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 30);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = NoteObject(
          uid: uidParam,
          text: textParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          originTypeValue: originTypeValueParam,
          statusValue: statusValueParam,
          sourceDurationMs: sourceDurationMsParam,
          transcriptionModelId: transcriptionModelIdParam,
          transcriptionLanguageCode: transcriptionLanguageCodeParam,
          transcriptionTaskTypeValue: transcriptionTaskTypeValueParam,
          transcribedAt: transcribedAtParam,
          transcriptionProcessingTimeMs: transcriptionProcessingTimeMsParam,
          transcriptionStrategyValue: transcriptionStrategyValueParam,
          transcriptionUsedVad: transcriptionUsedVadParam,
          transcriptionFellBackFromVad: transcriptionFellBackFromVadParam,
          transcriptionEmotionLabel: transcriptionEmotionLabelParam,
          transcriptionEventLabel: transcriptionEventLabelParam,
          transcriptionUsedItn: transcriptionUsedItnParam,
          transcriptionUsedPunctuation: transcriptionUsedPunctuationParam,
          failureReasonValue: failureReasonValueParam,
          id: idParam,
        );
        object.folder.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        object.folder.attach(store);
        object.audio.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        object.audio.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<NoteObject>(
          object.tags,
          store,
          obx_int.RelInfo<NoteObject>.toMany(1, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<NoteObject>(
          object.transcriptionSegments,
          store,
          obx_int.RelInfo<NoteTranscriptionSegmentObject>.toOneBacklink(
            9,
            object.id,
            (NoteTranscriptionSegmentObject srcObject) => srcObject.note,
          ),
        );
        return object;
      },
    ),
    TagObject: obx_int.EntityDefinition<TagObject>(
      model: _entities[2],
      toOneRelations: (TagObject object) => [],
      toManyRelations: (TagObject object) => {
        obx_int.RelInfo<NoteObject>.toManyBacklink(1, object.id): object.notes,
      },
      getId: (TagObject object) => object.id,
      setId: (TagObject object, int id) {
        object.id = id;
      },
      objectToFB: (TagObject object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.colorValue);
        fbb.addInt64(3, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0) / 1000)
              .round(),
          isUtc: true,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final colorValueParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final object = TagObject(
          name: nameParam,
          createdAt: createdAtParam,
          id: idParam,
          colorValue: colorValueParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<TagObject>(
          object.notes,
          store,
          obx_int.RelInfo<NoteObject>.toManyBacklink(1, object.id),
        );
        return object;
      },
    ),
    DownloadedModelObject: obx_int.EntityDefinition<DownloadedModelObject>(
      model: _entities[3],
      toOneRelations: (DownloadedModelObject object) => [],
      toManyRelations: (DownloadedModelObject object) => {},
      getId: (DownloadedModelObject object) => object.id,
      setId: (DownloadedModelObject object, int id) {
        object.id = id;
      },
      objectToFB: (DownloadedModelObject object, fb.Builder fbb) {
        final modelIdOffset = fbb.writeString(object.modelId);
        final modelDirNameOffset = fbb.writeString(object.modelDirName);
        final localPathOffset = fbb.writeString(object.localPath);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, modelIdOffset);
        fbb.addOffset(2, modelDirNameOffset);
        fbb.addOffset(3, localPathOffset);
        fbb.addBool(4, object.isSelected);
        fbb.addInt64(5, object.downloadedAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(6, object.fileSizeBytes);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final modelIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final modelDirNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final localPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final downloadedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0) / 1000)
              .round(),
          isUtc: true,
        );
        final isSelectedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final fileSizeBytesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = DownloadedModelObject(
          modelId: modelIdParam,
          modelDirName: modelDirNameParam,
          localPath: localPathParam,
          downloadedAt: downloadedAtParam,
          isSelected: isSelectedParam,
          fileSizeBytes: fileSizeBytesParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    NoteAudioObject: obx_int.EntityDefinition<NoteAudioObject>(
      model: _entities[4],
      toOneRelations: (NoteAudioObject object) => [],
      toManyRelations: (NoteAudioObject object) => {},
      getId: (NoteAudioObject object) => object.id,
      setId: (NoteAudioObject object, int id) {
        object.id = id;
      },
      objectToFB: (NoteAudioObject object, fb.Builder fbb) {
        final folderUidOffset = object.folderUid == null
            ? null
            : fbb.writeString(object.folderUid!);
        final relativePathOffset = fbb.writeString(object.relativePath);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, folderUidOffset);
        fbb.addOffset(2, relativePathOffset);
        fbb.addInt64(3, object.sizeBytes);
        fbb.addInt64(4, object.sampleRate);
        fbb.addInt64(5, object.durationMs);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final relativePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sizeBytesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final sampleRateParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final durationMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final folderUidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = NoteAudioObject(
          relativePath: relativePathParam,
          sizeBytes: sizeBytesParam,
          sampleRate: sampleRateParam,
          durationMs: durationMsParam,
          folderUid: folderUidParam,
          id: idParam,
        );

        return object;
      },
    ),
    NoteTranscriptionSegmentObject:
        obx_int.EntityDefinition<NoteTranscriptionSegmentObject>(
          model: _entities[5],
          toOneRelations: (NoteTranscriptionSegmentObject object) => [
            object.note,
          ],
          toManyRelations: (NoteTranscriptionSegmentObject object) => {},
          getId: (NoteTranscriptionSegmentObject object) => object.id,
          setId: (NoteTranscriptionSegmentObject object, int id) {
            object.id = id;
          },
          objectToFB: (NoteTranscriptionSegmentObject object, fb.Builder fbb) {
            final textOffset = fbb.writeString(object.text);
            final languageCodeOffset = object.languageCode == null
                ? null
                : fbb.writeString(object.languageCode!);
            final tokensJsonOffset = object.tokensJson == null
                ? null
                : fbb.writeString(object.tokensJson!);
            final tokenTimestampsMsJsonOffset =
                object.tokenTimestampsMsJson == null
                ? null
                : fbb.writeString(object.tokenTimestampsMsJson!);
            fbb.startTable(10);
            fbb.addInt64(0, object.id);
            fbb.addInt64(1, object.index);
            fbb.addOffset(2, textOffset);
            fbb.addInt64(3, object.startMs);
            fbb.addInt64(4, object.endMs);
            fbb.addOffset(5, languageCodeOffset);
            fbb.addOffset(6, tokensJsonOffset);
            fbb.addOffset(7, tokenTimestampsMsJsonOffset);
            fbb.addInt64(8, object.note.targetId);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final indexParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              6,
              0,
            );
            final textParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 8, '');
            final startMsParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              10,
              0,
            );
            final endMsParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              12,
              0,
            );
            final languageCodeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 14);
            final tokensJsonParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 16);
            final tokenTimestampsMsJsonParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 18);
            final idParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final object = NoteTranscriptionSegmentObject(
              index: indexParam,
              text: textParam,
              startMs: startMsParam,
              endMs: endMsParam,
              languageCode: languageCodeParam,
              tokensJson: tokensJsonParam,
              tokenTimestampsMsJson: tokenTimestampsMsJsonParam,
              id: idParam,
            );
            object.note.targetId = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              20,
              0,
            );
            object.note.attach(store);
            return object;
          },
        ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FolderObject] entity fields to define ObjectBox queries.
class FolderObject_ {
  /// See [FolderObject.id].
  static final id = obx.QueryIntegerProperty<FolderObject>(
    _entities[0].properties[0],
  );

  /// See [FolderObject.uid].
  static final uid = obx.QueryStringProperty<FolderObject>(
    _entities[0].properties[1],
  );

  /// See [FolderObject.name].
  static final name = obx.QueryStringProperty<FolderObject>(
    _entities[0].properties[2],
  );

  /// See [FolderObject.description].
  static final description = obx.QueryStringProperty<FolderObject>(
    _entities[0].properties[3],
  );

  /// See [FolderObject.colorValue].
  static final colorValue = obx.QueryIntegerProperty<FolderObject>(
    _entities[0].properties[4],
  );

  /// See [FolderObject.iconRef].
  static final iconRef = obx.QueryStringProperty<FolderObject>(
    _entities[0].properties[5],
  );

  /// See [FolderObject.updatedAt].
  static final updatedAt = obx.QueryDateNanoProperty<FolderObject>(
    _entities[0].properties[6],
  );

  /// See [FolderObject.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<FolderObject>(
    _entities[0].properties[7],
  );

  /// see [FolderObject.notes]
  static final notes = obx.QueryBacklinkToMany<NoteObject, FolderObject>(
    NoteObject_.folder,
  );
}

/// [NoteObject] entity fields to define ObjectBox queries.
class NoteObject_ {
  /// See [NoteObject.id].
  static final id = obx.QueryIntegerProperty<NoteObject>(
    _entities[1].properties[0],
  );

  /// See [NoteObject.uid].
  static final uid = obx.QueryStringProperty<NoteObject>(
    _entities[1].properties[1],
  );

  /// See [NoteObject.text].
  static final text = obx.QueryStringProperty<NoteObject>(
    _entities[1].properties[2],
  );

  /// See [NoteObject.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<NoteObject>(
    _entities[1].properties[3],
  );

  /// See [NoteObject.updatedAt].
  static final updatedAt = obx.QueryDateNanoProperty<NoteObject>(
    _entities[1].properties[4],
  );

  /// See [NoteObject.folder].
  static final folder = obx.QueryRelationToOne<NoteObject, FolderObject>(
    _entities[1].properties[5],
  );

  /// See [NoteObject.audio].
  static final audio = obx.QueryRelationToOne<NoteObject, NoteAudioObject>(
    _entities[1].properties[6],
  );

  /// See [NoteObject.statusValue].
  static final statusValue = obx.QueryIntegerProperty<NoteObject>(
    _entities[1].properties[7],
  );

  /// See [NoteObject.failureReasonValue].
  static final failureReasonValue = obx.QueryIntegerProperty<NoteObject>(
    _entities[1].properties[8],
  );

  /// See [NoteObject.originTypeValue].
  static final originTypeValue = obx.QueryIntegerProperty<NoteObject>(
    _entities[1].properties[9],
  );

  /// See [NoteObject.sourceDurationMs].
  static final sourceDurationMs = obx.QueryIntegerProperty<NoteObject>(
    _entities[1].properties[10],
  );

  /// See [NoteObject.transcriptionModelId].
  static final transcriptionModelId = obx.QueryStringProperty<NoteObject>(
    _entities[1].properties[11],
  );

  /// See [NoteObject.transcriptionLanguageCode].
  static final transcriptionLanguageCode = obx.QueryStringProperty<NoteObject>(
    _entities[1].properties[12],
  );

  /// See [NoteObject.transcribedAt].
  static final transcribedAt = obx.QueryDateNanoProperty<NoteObject>(
    _entities[1].properties[13],
  );

  /// See [NoteObject.transcriptionTaskTypeValue].
  static final transcriptionTaskTypeValue =
      obx.QueryIntegerProperty<NoteObject>(_entities[1].properties[14]);

  /// See [NoteObject.transcriptionProcessingTimeMs].
  static final transcriptionProcessingTimeMs =
      obx.QueryIntegerProperty<NoteObject>(_entities[1].properties[15]);

  /// See [NoteObject.transcriptionStrategyValue].
  static final transcriptionStrategyValue =
      obx.QueryIntegerProperty<NoteObject>(_entities[1].properties[16]);

  /// See [NoteObject.transcriptionUsedVad].
  static final transcriptionUsedVad = obx.QueryBooleanProperty<NoteObject>(
    _entities[1].properties[17],
  );

  /// See [NoteObject.transcriptionFellBackFromVad].
  static final transcriptionFellBackFromVad =
      obx.QueryBooleanProperty<NoteObject>(_entities[1].properties[18]);

  /// See [NoteObject.transcriptionEmotionLabel].
  static final transcriptionEmotionLabel = obx.QueryStringProperty<NoteObject>(
    _entities[1].properties[19],
  );

  /// See [NoteObject.transcriptionEventLabel].
  static final transcriptionEventLabel = obx.QueryStringProperty<NoteObject>(
    _entities[1].properties[20],
  );

  /// See [NoteObject.transcriptionUsedItn].
  static final transcriptionUsedItn = obx.QueryBooleanProperty<NoteObject>(
    _entities[1].properties[21],
  );

  /// See [NoteObject.transcriptionUsedPunctuation].
  static final transcriptionUsedPunctuation =
      obx.QueryBooleanProperty<NoteObject>(_entities[1].properties[22]);

  /// see [NoteObject.tags]
  static final tags = obx.QueryRelationToMany<NoteObject, TagObject>(
    _entities[1].relations[0],
  );

  /// see [NoteObject.transcriptionSegments]
  static final transcriptionSegments =
      obx.QueryBacklinkToMany<NoteTranscriptionSegmentObject, NoteObject>(
        NoteTranscriptionSegmentObject_.note,
      );
}

/// [TagObject] entity fields to define ObjectBox queries.
class TagObject_ {
  /// See [TagObject.id].
  static final id = obx.QueryIntegerProperty<TagObject>(
    _entities[2].properties[0],
  );

  /// See [TagObject.name].
  static final name = obx.QueryStringProperty<TagObject>(
    _entities[2].properties[1],
  );

  /// See [TagObject.colorValue].
  static final colorValue = obx.QueryIntegerProperty<TagObject>(
    _entities[2].properties[2],
  );

  /// See [TagObject.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<TagObject>(
    _entities[2].properties[3],
  );
}

/// [DownloadedModelObject] entity fields to define ObjectBox queries.
class DownloadedModelObject_ {
  /// See [DownloadedModelObject.id].
  static final id = obx.QueryIntegerProperty<DownloadedModelObject>(
    _entities[3].properties[0],
  );

  /// See [DownloadedModelObject.modelId].
  static final modelId = obx.QueryStringProperty<DownloadedModelObject>(
    _entities[3].properties[1],
  );

  /// See [DownloadedModelObject.modelDirName].
  static final modelDirName = obx.QueryStringProperty<DownloadedModelObject>(
    _entities[3].properties[2],
  );

  /// See [DownloadedModelObject.localPath].
  static final localPath = obx.QueryStringProperty<DownloadedModelObject>(
    _entities[3].properties[3],
  );

  /// See [DownloadedModelObject.isSelected].
  static final isSelected = obx.QueryBooleanProperty<DownloadedModelObject>(
    _entities[3].properties[4],
  );

  /// See [DownloadedModelObject.downloadedAt].
  static final downloadedAt = obx.QueryDateNanoProperty<DownloadedModelObject>(
    _entities[3].properties[5],
  );

  /// See [DownloadedModelObject.fileSizeBytes].
  static final fileSizeBytes = obx.QueryIntegerProperty<DownloadedModelObject>(
    _entities[3].properties[6],
  );
}

/// [NoteAudioObject] entity fields to define ObjectBox queries.
class NoteAudioObject_ {
  /// See [NoteAudioObject.id].
  static final id = obx.QueryIntegerProperty<NoteAudioObject>(
    _entities[4].properties[0],
  );

  /// See [NoteAudioObject.folderUid].
  static final folderUid = obx.QueryStringProperty<NoteAudioObject>(
    _entities[4].properties[1],
  );

  /// See [NoteAudioObject.relativePath].
  static final relativePath = obx.QueryStringProperty<NoteAudioObject>(
    _entities[4].properties[2],
  );

  /// See [NoteAudioObject.sizeBytes].
  static final sizeBytes = obx.QueryIntegerProperty<NoteAudioObject>(
    _entities[4].properties[3],
  );

  /// See [NoteAudioObject.sampleRate].
  static final sampleRate = obx.QueryIntegerProperty<NoteAudioObject>(
    _entities[4].properties[4],
  );

  /// See [NoteAudioObject.durationMs].
  static final durationMs = obx.QueryIntegerProperty<NoteAudioObject>(
    _entities[4].properties[5],
  );
}

/// [NoteTranscriptionSegmentObject] entity fields to define ObjectBox queries.
class NoteTranscriptionSegmentObject_ {
  /// See [NoteTranscriptionSegmentObject.id].
  static final id = obx.QueryIntegerProperty<NoteTranscriptionSegmentObject>(
    _entities[5].properties[0],
  );

  /// See [NoteTranscriptionSegmentObject.index].
  static final index = obx.QueryIntegerProperty<NoteTranscriptionSegmentObject>(
    _entities[5].properties[1],
  );

  /// See [NoteTranscriptionSegmentObject.text].
  static final text = obx.QueryStringProperty<NoteTranscriptionSegmentObject>(
    _entities[5].properties[2],
  );

  /// See [NoteTranscriptionSegmentObject.startMs].
  static final startMs =
      obx.QueryIntegerProperty<NoteTranscriptionSegmentObject>(
        _entities[5].properties[3],
      );

  /// See [NoteTranscriptionSegmentObject.endMs].
  static final endMs = obx.QueryIntegerProperty<NoteTranscriptionSegmentObject>(
    _entities[5].properties[4],
  );

  /// See [NoteTranscriptionSegmentObject.languageCode].
  static final languageCode =
      obx.QueryStringProperty<NoteTranscriptionSegmentObject>(
        _entities[5].properties[5],
      );

  /// See [NoteTranscriptionSegmentObject.tokensJson].
  static final tokensJson =
      obx.QueryStringProperty<NoteTranscriptionSegmentObject>(
        _entities[5].properties[6],
      );

  /// See [NoteTranscriptionSegmentObject.tokenTimestampsMsJson].
  static final tokenTimestampsMsJson =
      obx.QueryStringProperty<NoteTranscriptionSegmentObject>(
        _entities[5].properties[7],
      );

  /// See [NoteTranscriptionSegmentObject.note].
  static final note =
      obx.QueryRelationToOne<NoteTranscriptionSegmentObject, NoteObject>(
        _entities[5].properties[8],
      );
}
